# Generated by Django 3.2.23 on 2024-02-10 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240210_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='friendly_name',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
    ]
