# Generated by Django 3.2.23 on 2024-02-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20240211_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
