# Generated by Django 3.2.23 on 2024-02-11 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_on',
        ),
    ]
