# Generated by Django 3.2.23 on 2024-02-11 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20240211_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
