# Generated by Django 3.2.23 on 2024-02-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogcomment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
