# Generated by Django 3.2.23 on 2024-02-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogcomment_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='updated_on',
        ),
    ]
