# Generated by Django 3.2.23 on 2024-02-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240203_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
    ]
