# Generated by Django 3.2.23 on 2024-02-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
